---
- name: Download tar.gz liferay+wildfly-bundle
  ansible.builtin.command:
    argv: 
      - curl
      - "{{ bundle_uri }}"
      - -L
      - -o
      - /opt/liferay_portal


- name: Create liferay home directory
  ansible.builtin.file:
    path: "{{ liferay_home_dir }}"
    state: directory
    mode: '0700'
  become: True

- name: Extract liferay+wildfly bundle archive into liferay home dir
  ansible.builtin.unarchive:
    src: /opt/liferay_portal
    dest: "{{ liferay_home_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Download appropteate postgres.jar version
  ansible.builtin.command:
    argv:
      - curl
      - "{{ postgresql_jar_link }}"
      - -o 
      - "{{liferay_home_dir}}/wildfly-11.0.0/modules/com/liferay/portal/main/postgresql.jar"


- name: Add liferay portal config
  ansible.builtin.template:
    src: liferay_bundle.cfg.j2
    dest: "{{liferay_home_dir}}/portal-setup-wizard.properties"
    mode: 0600

- name: Create wildfly service dscription file for systemd
  ansible.builtin.template:
    src: wildfly_11.service.j2
    dest: /etc/systemd/system/wildfly.service
    mode: 0744
  become: True

- name: Enable and start systemd service
  ansible.builtin.systemd:
    name: wildfly
    state: started
    daemon_reload: True
    enabled: True

- name: Wait for WildFly to start up before proceeding.
  uri:
    url: "http://127.0.0.1:8080"
    method: GET
    return_content: "yes"
    timeout: 5
    body_format: raw
    follow_redirects: "no"
    status_code: 200,403
  register: result
  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
  retries: 60
  delay: 5
  changed_when: false
  check_mode: false

