---
- name: Install epel-release
  yum:
    name: 
       - epel-release
    state: latest

- name: Install unzip and java
  yum:
    name: 
       - unzip
       - java-11-openjdk-devel
       - wget 
       - curl
    state: latest

- name: Ensure Java is installed.
  package:
    name: java-11-openjdk-devel
    state: present
