---
jenkins_package_state: present

jenkins_version: 2.324
jenkins_url: https://get.jenkins.io/redhat/jenkins-2.324-1.1.noarch.rpm
jenkins_key: https://get.jenkins.io/redhat/jenkins.io.key
jenkins_repo_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
jenkins_repo_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
jenkins_home: /var/lib/jenkins
jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"