---
# https://docs.ansible.com/ansible/2.9/modules/jenkins_plugin_module.html

- name: Plugin installation
  hosts: localhost
  vars:
    - jenkins_path: /var/lib/jenkins
    - jenkins_ip_external: 127.0.0.1
    - jenkins_port: 8080
    - jenkins_init_file: 1
    - jenkins_url_prefix: ""
    - jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    - jenkins_init_changes:
      - option: "JENKINS_ARGS"
        value: "--prefix={{ jenkins_url_prefix }}"
      - option: "JENKINS_JAVA_OPTIONS"
        value: "{{ jenkins_java_options }}"


  tasks:
  - name: Check if jenkins_init_file exists.
    stat:
      path: "{{ jenkins_init_file }}"
    register: jenkins_init_file_stat

  - name: Ensure jenkins_init_file exists.
    file:
      path: "{{ jenkins_init_file }}"
      state: touch
      mode: 0644
    when: not jenkins_init_file_stat.stat.exists

  - name: Wait for Jenkins to start up before proceeding.
    uri:
      url: "http://{{ jenkins_ip_external }}:{{ jenkins_port }}{{ jenkins_url_prefix }}/cli/"
      method: GET
      return_content: "yes"
      timeout: 5
      body_format: raw
      follow_redirects: "no"
      status_code: 200,403
    register: result
    until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
    retries: 60
    delay: 5
    changed_when: false
    check_mode: false

  - name: disable security
    ansible.builtin.lineinfile:
      path: "{{ jenkins_path }}/config.xml"
      regexp: '^<useSecurity>'
      line: '<useSecurity>false'
      insertbefore: '^</useSecurity>'
  
  # put in handlers
  - name: restart jenkins
    systemd:
      daemon_reload: true
      name: jenkins
      state: restarted
      enabled: true

  - name: Jenkins response
    ansible.builtin.uri:
      url: "http://127.0.0.1:8080/jenkins"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 100
    delay: 5

  - name: Download jenkins-cli.jar
    ansible.builtin.get_url:
      url: "http://{{ jenkins_ip_external }}:8080/jenkins/jnlpJars/jenkins-cli.jar"
      dest: "~/"

  - name: Add User admin to jenkins
    ansible.builtin.shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("admin","admin")' | java -jar ~/jenkins-cli.jar -s "http://{{ jenkins_ip_external }}:{{ jenkins_port }}/jenkins/" -auth admin:admin -noKeyAuth groovy = – 

  - name: Install ansible plugin
    jenkins_plugin:
      name: ansible
      url_username: admin
      url_password: admin
      url: "http://{{ jenkins_ip_external }}:8080/jenkins"
      timeout: 1000

  - name: Config ansible plugin
    ansible.builtin.shell: "java -jar ~/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/install-plugin ansible"  
    loop:
      - ws-cleanup # Workspace Cleanup
      - workflow-aggregator # Pipeline
      - pipeline-stage-view # Pipeline: Stage View
      - git # Git
      - ansible # Ansible
      - ansicolor # AnsiColor

  - name: Add docker job to jenkins
    ansible.builtin.shell: "java -jar ~/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ create-job Docker_installation < /configd.xml"

  - name: Add wildfly job to jenkins
    ansible.builtin.shell: "java -jar ~/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ create-job Wildfly_installation < /configw.xml"
    
  # - name: Trigger remote build
  #   ansible.builtin.shell: |
  #     curl {{ jenkins_node_ip }}/job/Docker_installation/build?token=playbooktkn1
  #     curl {{ jenkins_node_ip }}/job/Docker_installation/build?token=playbooktkn2
        
# Use the following URL to trigger build remotely: 
# [jenkins_node_ip]/job/Docker_installation/build?token=playbooktkn[1/2]