---
- name: Update system and install ansibe
  hosts: jenkins_node

  roles:
    - name: ansible_install

- name: Install Jenkins and java
  hosts: jenkins_node

  roles:
    - name: jenkins_install
      become: true
      become_user: root

- name: Start jenkins_job
  hosts: jenkins_node

  tasks:
    - name: start playbooktk
      ansible.builtin.shell: |
        script jenkins_job_output.txt
        cd repo_with_keys/Ansible
        ansible-playbook -vvv -i inventory jenkins_job.yml && exit