---
- name: Update system and install ansibe
  hosts: jenkins_node

  roles:
    - name: ansible_install

- name: Install Jenkins and java
  hosts: jenkins_node
  become: true
  user: root

  roles:
    - name: jenkins_install

