  - name: Plugin installation
    hosts: jenkins_node
    vars:
      - jenkins_path: /var/lib/jenkins
      - jenkins_ip_external: 127.0.0.1
      - jenkins_port: 8080
      - item: ansible

    tasks:    
    - name: Install ansible plugin   
      ansible.builtin.shell: "java -jar {{jenkins_path}}/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/install-plugin {{ item }}"
        jenkins_plugin:     
          name: "{{ item }}"     
          url: "http://127.0.0.1:8080/jenkins"    
          timeout: 1000   
        loop:    
          - ws-cleanup # Workspace Cleanup   
          - workflow-aggregator # Pipeline    
          - pipeline-stage-view # Pipeline: Stage View  
          - git # Git   
          - ansible # Ansible     
          - ansicolor # AnsiColor 

    - name: Add docker job to jenkins  
      ansible.builtin.shell: "java -jar /root/.jenkins/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ create-job Docker_installation < /configd.xml"

    - name: Add wildfly job to jenkins  
      ansible.builtin.shell: "java -jar /root/.jenkins/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ create-job Wildfly_installation < /configw.xml"

# Use the following URL to trigger build remotely: 
# [jenkins_node_ip]/job/Docker_installation/build?token=playbooktkn[1/2]