  - name: System confuguration
    hosts: jenkins_node

    tasks:
    - name: Prepare CentOS
      ansible.builtin.shell: |
        cd
        mkdir repo_with_keys
        tar -xf repo.tar -C repo_with_keys
        sudo yum -y update
        sudo yum -y update ca-certificates
        sudo yum -y install epel-release
        sudo yum -y install libselinux-python3
        sudo yum -y install curl
        sudo yum install -y python3 python3-pip
        pip3 install --user --upgrade pip && cd && cd repo_with_keys && sudo python3 add_known_hosts.py

      vars:
        ansible_python_interpreter: /usr/bin/python
    
    - name: Ansible installation
      ansible.builtin.shell: |
        python -m pip install ansible
      vars:
        ansible_python_interpreter: /usr/bin/python

  - name: Jenkins installation
    hosts: jenkins_node
    become: yes
    become_user: root

    tasks:
    - name: Installing Git. Clone.
      ansible.builtin.shell: |
        yum -y install git
        git --version
        git clone -b pre_release https://gitlab.com/devops_netcraker/repo.git
       
    - name: Ansible installation
      ansible.builtin.shell: |
        pip3 install ansible
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install java
      yum:
        name: java-11-openjdk-devel
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Install jenkins
      yum:
        name: jenkins
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python


    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

# run by ansible-playbook -i /path/to/inventory setup.yml
