  - name: Jenkins installation
    hosts: jenkins_node
    become: yes
    become_user: root

    tasks:
    - name: Prepare CentOS
      ansible.builtin.shell: |
        yum -y update
        yum -y update ca-certificates
        yum -y install epel-release
        yum -y install libselinux-python3
      vars:
	      ansible_python_interpreter: /usr/bin/python

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install java
      yum:
        name: java-11-openjdk-devel
        state: present
      vars:
	      ansible_python_interpreter: /usr/bin/python

    - name: Install jenkins
      yum:
        name: jenkins
        state: present
      vars:
	      ansible_python_interpreter: /usr/bin/python


    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

# run by ansible-playbook -i /path/to/inventory setup.yml
