---
    - name: Prepare CentOS
      ansible.builtin.shell: |
        mkdir /opt/repo_with_keys
        tar -xf /home/azureuser/repo.tar -C /opt/repo_with_keys
        yum -y install ca-certificates
        yum -y install epel-release
        yum -y install python3
        yum -y install libselinux-python3
        yum -y install curl initscripts git
        cd /opt/repo_with_keys && python3 add_known_hosts.py

      vars:
        ansible_python_interpreter: /usr/bin/python
    
    - name: Ansible installation
      ansible.builtin.shell: |
        yum -y install ansible