---
jenkins_home: /var/lib/jenkins
jenkins_ip_external: 127.0.0.1
jenkins_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_init_file: /etc/sysconfig/jenkins
jenkins_url_prefix: ""
jenkins_java_options: -Djenkins.install.runSetupWizard=false
jenkins_http_port_param: JENKINS_PORT
jenkins_java_options_env_var: JENKINS_JAVA_OPTIONS
jenkins_process_user: root
jenkins_process_group: "{{ jenkins_process_user }}"
jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"